version: "3.8"
services:
  server:
    build: ./FCScoreServer
    ports:
      - 5000:5000
  client:
    build: ./FCScoreClient
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:5000