FROM python:3.11.4-slim-buster

LABEL maintainer "Thomas David, thomasdavid0@gmail.com"

# set working directory in container
WORKDIR /usr/src/app

# Copy and install packages
COPY requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

# Copy app folder to app folder in container
COPY /app /usr/src/app/

# Changing to non-root user
RUN useradd -m appUser
USER appUser

CMD gunicorn --bind 0.0.0.0:$PORT app:server